### ISSUE TITLE
Receipt validation: inconsistently looking at version number vs. build number?

### ISSUE THREAD

**Issue by dmauer** [steprescott/SCPStoreKitManager#15]
Unless I'm missing something, it looks to me that the method `-(void)verifyReceiptAtPath:(NSString *)receiptPath success:(Success)successBlock failure:(Failure)failureBlock` is always going to fail, because it first checks to confirm that the `_bundleVersion` is equal to the app's `CFBundleShortVersionString` (e.g. "3.1.4"), but then after it receives the receipt from Apple, it checks that same `_bundleVersion` against `[receipt bundleVersion]`, which appears to instead contain the build number (e.g. "107").  At least, running my app in the sandbox, I get the build number in `[receipt bundleVersion]`.  Am I doing something wrong, or is this a bug?  Thanks.

**Comment by steprescott** [comment]
Will look into this. Thanks for reporting it.

**Comment by rafaelmaroxa** [comment]
Possible duplicate of #13, which was fixed by #14.

**Comment by remiMargaria** [comment]
I have the same problem, the issue is fixed but the Podspec is not updated, CFBundleShortVersionString should be replaced by CFBundleVersion in verifyReceiptAtPath.

**Comment by steprescott** [comment]
Thanks @rafaelmaroxa, I am currently focusing on my Masters so will update the pod spec when I can. Sorry for this.

**Comment by dmauer** [comment]
Yep, that was it -- podspec. Thanks.
