### ISSUE TITLE
restorePurchasesPaymentTransactionStateRestored cancel enter apple id and password

### ISSUE THREAD

**Issue by matrosovDev** [steprescott/SCPStoreKitManager#19]
When I use restorePurchasesPaymentTransactionStateRestored it allows me to enter apple id and password. But when I add it and it's not correct then I never got an error or if press cancel button it never get some failure block of that method. Maybe it's simulator issue.

**Comment by steprescott** [comment]
StoreKit does not work in the simulator, only on the device with a test iTunes Connect account.
